name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Build Docker image
        run: docker build -t user-management-api .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag user-management-api ${{ secrets.DOCKER_USERNAME }}/user-management-api
          docker push ${{ secrets.DOCKER_USERNAME }}/user-management-api

      - name: Deploy to Production
        run: |
          # Add deployment commands here
